version: '3'

services:
  postgis:
    image: mdillon/postgis
    restart: always
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    expose:
      - "5432"
  web:
    restart: always
    build: .
    command: ["./wait-for-it.sh", "postgis:5432", "-t", "0", "--", "./init_web.sh"]
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    links:
      - "postgis:postgis"
    depends_on:
      - "postgis"
