# Generated by Django 2.1.2 on 2018-10-12 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personnels', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='branch',
            options={'verbose_name': 'branch', 'verbose_name_plural': 'branch'},
        ),
        migrations.AddField(
            model_name='branch',
            name='name',
            field=models.CharField(blank=True, max_length=30, verbose_name='branch name'),
        ),
        migrations.AlterField(
            model_name='branch',
            name='facade',
            field=models.ImageField(blank=True, null=True, upload_to='facades/'),
        ),
    ]
