# Generated by Django 2.1.2 on 2018-10-12 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personnels', '0003_auto_20181012_1759'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='personnel',
            managers=[
            ],
        ),
        migrations.RemoveField(
            model_name='personnel',
            name='date_joined',
        ),
        migrations.RemoveField(
            model_name='personnel',
            name='email',
        ),
        migrations.RemoveField(
            model_name='personnel',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='personnel',
            name='is_staff',
        ),
        migrations.RemoveField(
            model_name='personnel',
            name='is_superuser',
        ),
        migrations.RemoveField(
            model_name='personnel',
            name='last_login',
        ),
        migrations.RemoveField(
            model_name='personnel',
            name='password',
        ),
        migrations.RemoveField(
            model_name='personnel',
            name='username',
        ),
        migrations.AlterField(
            model_name='personnel',
            name='last_name',
            field=models.CharField(blank=True, max_length=30, verbose_name='last name'),
        ),
    ]
