# Generated by Django 2.1.2 on 2018-10-13 22:00

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('branches', '0002_auto_20181013_2048'),
    ]

    operations = [
        migrations.AddField(
            model_name='branch',
            name='point',
            field=django.contrib.gis.db.models.fields.PointField(blank=True, null=True, srid=4326),
        ),
    ]
