# Generated by Django 2.1.2 on 2018-10-14 10:07

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('branches', '0003_branch_point'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='branch',
            options={'permissions': (('change_coordinates', 'Can change coordinates'),), 'verbose_name': 'branch', 'verbose_name_plural': 'branches'},
        ),
        migrations.AlterField(
            model_name='branch',
            name='point',
            field=django.contrib.gis.db.models.fields.PointField(blank=True, help_text='Example: SRID=4326;POINT (76.56249397744735 52.91331451667325)', null=True, srid=4326),
        ),
    ]
